# Generated by Django 4.1.7 on 2023-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bid', models.AutoField(db_column='BID', primary_key=True, serialize=False)),
                ('bdate', models.IntegerField(db_column='BDate')),
                ('byear', models.IntegerField(db_column='BYear')),
                ('bmonth', models.IntegerField(db_column='BMonth')),
                ('current_reading', models.IntegerField(db_column='Current_Reading')),
                ('prev_reading', models.IntegerField(db_column='Prev_Reading')),
                ('bamount', models.IntegerField(db_column='Bamount')),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('scno', models.IntegerField(db_column='SCNO')),
                ('cusid', models.AutoField(db_column='CUSID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=255)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('mobileno', models.IntegerField(db_column='MobileNo')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demandrate',
            fields=[
                ('drid', models.AutoField(db_column='DRID', primary_key=True, serialize=False)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('iscurrent', models.IntegerField(blank=True, db_column='IsCurrent', null=True)),
                ('effective_date', models.DateField(blank=True, db_column='Effective_date', null=True)),
            ],
            options={
                'db_table': 'demandrate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demandtype',
            fields=[
                ('demand_type_id', models.AutoField(db_column='Demand_Type_ID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'demandtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('pdate', models.IntegerField(blank=True, db_column='PDate', null=True)),
                ('pamount', models.IntegerField(blank=True, db_column='PAmount', null=True)),
                ('rebate_amt', models.IntegerField(blank=True, db_column='Rebate_Amt', null=True)),
                ('fine_amt', models.IntegerField(blank=True, db_column='Fine_Amt', null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('poid', models.AutoField(db_column='POID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'payment_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(db_column='Branch_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': True,
            },
        ),
    ]
