# Generated by Django 4.1.7 on 2023-05-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'managed': True},
        ),
    ]
