# Generated by Django 4.1.7 on 2023-05-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_paymentoption_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandtype',
            options={'managed': True},
        ),
    ]
