# Generated by Django 4.1.7 on 2023-05-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_demandtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
    ]
