# Generated by Django 4.1.7 on 2023-05-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='Branch_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.branch'),
        ),
        migrations.AddField(
            model_name='customer',
            name='demand_type',
            field=models.ForeignKey(blank=True, db_column='Demand_type_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.demandtype'),
        ),
    ]
