# Generated by Django 4.1.7 on 2023-05-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_branch_customer_demand_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='demand_type',
            field=models.ForeignKey(blank=True, db_column='Demand_type_ID', default='Free', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.demandtype'),
        ),
    ]
