# Generated by Django 4.1.7 on 2023-05-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_customer_demand_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandrate',
            options={'managed': True},
        ),
    ]
