# Generated by Django 4.1.7 on 2023-05-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_demandrate_demand_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True},
        ),
    ]
