# Generated by Django 4.1.7 on 2023-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_cusid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, db_column='DateOfBirth', null=True),
        ),
    ]
