# Generated by Django 4.1.7 on 2023-06-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_customer_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True},
        ),
    ]
