# Generated by Django 4.1.7 on 2023-06-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(blank=True, db_column='BID', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(blank=True, db_column='Payment_type_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentoption'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pdate',
            field=models.DateField(blank=True, db_column='PDate', null=True),
        ),
    ]
