# Generated by Django 4.1.7 on 2023-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_payment_bid_payment_payment_type_alter_payment_pdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], db_column='Status', max_length=200, null=True),
        ),
    ]
