# Generated by Django 4.1.7 on 2023-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], db_column='Status', max_length=200, null=True),
        ),
    ]
