# Generated by Django 4.1.7 on 2023-06-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileno',
            field=models.IntegerField(db_column='MobileNo', max_length=10),
        ),
    ]
