# Generated by Django 4.1.7 on 2023-06-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_customer_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobileno',
            field=models.CharField(db_column='MobileNo', max_length=10),
        ),
    ]
