# Generated by Django 4.1.7 on 2023-06-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_customer_mobileno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentCus',
        ),
    ]
