# Generated by Django 4.1.7 on 2023-07-10 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_alter_paymentcus_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='Branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.branch'),
        ),
    ]
