# Generated by Django 4.1.7 on 2023-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_bill_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='branch',
        ),
    ]
